import type { Locale } from '../types'

/**
 * Hand-curated country / territory names: [한국어, English].
 * Short everyday names (no "공화국", "연방", "Republic of …" unless it is needed to tell two countries apart),
 * current spellings (튀르키예 / Türkiye, 체코 / Czechia, 에스와티니 / Eswatini, 북마케도니아 / North Macedonia),
 * and 대만 / Taiwan, 홍콩 / Hong Kong, 마카오 / Macao as their own entries.
 */
export const COUNTRY_NAMES: Record<string, [string, string]> = {
  ABW: ['아루바', 'Aruba'],
  AFG: ['아프가니스탄', 'Afghanistan'],
  AGO: ['앙골라', 'Angola'],
  AIA: ['앵귈라', 'Anguilla'],
  ALA: ['올란드 제도', 'Åland Islands'],
  ALB: ['알바니아', 'Albania'],
  AND: ['안도라', 'Andorra'],
  ARE: ['아랍에미리트', 'United Arab Emirates'],
  ARG: ['아르헨티나', 'Argentina'],
  ARM: ['아르메니아', 'Armenia'],
  ASM: ['아메리칸사모아', 'American Samoa'],
  ATA: ['남극', 'Antarctica'],
  ATF: ['프랑스령 남방 및 남극 지역', 'French Southern Territories'],
  ATG: ['앤티가 바부다', 'Antigua and Barbuda'],
  AUS: ['호주', 'Australia'],
  AUT: ['오스트리아', 'Austria'],
  AZE: ['아제르바이잔', 'Azerbaijan'],
  BDI: ['부룬디', 'Burundi'],
  BEL: ['벨기에', 'Belgium'],
  BEN: ['베냉', 'Benin'],
  BES: ['카리브 네덜란드', 'Caribbean Netherlands'],
  BFA: ['부르키나파소', 'Burkina Faso'],
  BGD: ['방글라데시', 'Bangladesh'],
  BGR: ['불가리아', 'Bulgaria'],
  BHR: ['바레인', 'Bahrain'],
  BHS: ['바하마', 'Bahamas'],
  BIH: ['보스니아 헤르체고비나', 'Bosnia and Herzegovina'],
  BLM: ['생바르텔레미', 'Saint Barthélemy'],
  BLR: ['벨라루스', 'Belarus'],
  BLZ: ['벨리즈', 'Belize'],
  BMU: ['버뮤다', 'Bermuda'],
  BOL: ['볼리비아', 'Bolivia'],
  BRA: ['브라질', 'Brazil'],
  BRB: ['바베이도스', 'Barbados'],
  BRN: ['브루나이', 'Brunei'],
  BTN: ['부탄', 'Bhutan'],
  BVT: ['부베섬', 'Bouvet Island'],
  BWA: ['보츠와나', 'Botswana'],
  CAF: ['중앙아프리카공화국', 'Central African Republic'],
  CAN: ['캐나다', 'Canada'],
  CCK: ['코코스 제도', 'Cocos (Keeling) Islands'],
  CHE: ['스위스', 'Switzerland'],
  CHL: ['칠레', 'Chile'],
  CHN: ['중국', 'China'],
  CIV: ['코트디부아르', "Côte d'Ivoire"],
  CMR: ['카메룬', 'Cameroon'],
  COD: ['콩고민주공화국', 'DR Congo'],
  COG: ['콩고공화국', 'Republic of the Congo'],
  COK: ['쿡 제도', 'Cook Islands'],
  COL: ['콜롬비아', 'Colombia'],
  COM: ['코모로', 'Comoros'],
  CPV: ['카보베르데', 'Cabo Verde'],
  CRI: ['코스타리카', 'Costa Rica'],
  CUB: ['쿠바', 'Cuba'],
  CUW: ['퀴라소', 'Curaçao'],
  CXR: ['크리스마스섬', 'Christmas Island'],
  CYM: ['케이맨 제도', 'Cayman Islands'],
  CYP: ['키프로스', 'Cyprus'],
  CZE: ['체코', 'Czechia'],
  DEU: ['독일', 'Germany'],
  DJI: ['지부티', 'Djibouti'],
  DMA: ['도미니카 연방', 'Dominica'],
  DNK: ['덴마크', 'Denmark'],
  DOM: ['도미니카 공화국', 'Dominican Republic'],
  DZA: ['알제리', 'Algeria'],
  ECU: ['에콰도르', 'Ecuador'],
  EGY: ['이집트', 'Egypt'],
  ERI: ['에리트레아', 'Eritrea'],
  ESH: ['서사하라', 'Western Sahara'],
  ESP: ['스페인', 'Spain'],
  EST: ['에스토니아', 'Estonia'],
  ETH: ['에티오피아', 'Ethiopia'],
  FIN: ['핀란드', 'Finland'],
  FJI: ['피지', 'Fiji'],
  FLK: ['포클랜드 제도', 'Falkland Islands'],
  FRA: ['프랑스', 'France'],
  FRO: ['페로 제도', 'Faroe Islands'],
  FSM: ['미크로네시아', 'Micronesia'],
  GAB: ['가봉', 'Gabon'],
  GBR: ['영국', 'United Kingdom'],
  GEO: ['조지아', 'Georgia'],
  GGY: ['건지섬', 'Guernsey'],
  GHA: ['가나', 'Ghana'],
  GIB: ['지브롤터', 'Gibraltar'],
  GIN: ['기니', 'Guinea'],
  GLP: ['과들루프', 'Guadeloupe'],
  GMB: ['감비아', 'Gambia'],
  GNB: ['기니비사우', 'Guinea-Bissau'],
  GNQ: ['적도기니', 'Equatorial Guinea'],
  GRC: ['그리스', 'Greece'],
  GRD: ['그레나다', 'Grenada'],
  GRL: ['그린란드', 'Greenland'],
  GTM: ['과테말라', 'Guatemala'],
  GUF: ['프랑스령 기아나', 'French Guiana'],
  GUM: ['괌', 'Guam'],
  GUY: ['가이아나', 'Guyana'],
  HKG: ['홍콩', 'Hong Kong'],
  HMD: ['허드 맥도널드 제도', 'Heard Island and McDonald Islands'],
  HND: ['온두라스', 'Honduras'],
  HRV: ['크로아티아', 'Croatia'],
  HTI: ['아이티', 'Haiti'],
  HUN: ['헝가리', 'Hungary'],
  IDN: ['인도네시아', 'Indonesia'],
  IMN: ['맨섬', 'Isle of Man'],
  IND: ['인도', 'India'],
  IOT: ['영국령 인도양 지역', 'British Indian Ocean Territory'],
  IRL: ['아일랜드', 'Ireland'],
  IRN: ['이란', 'Iran'],
  IRQ: ['이라크', 'Iraq'],
  ISL: ['아이슬란드', 'Iceland'],
  ISR: ['이스라엘', 'Israel'],
  ITA: ['이탈리아', 'Italy'],
  JAM: ['자메이카', 'Jamaica'],
  JEY: ['저지섬', 'Jersey'],
  JOR: ['요르단', 'Jordan'],
  JPN: ['일본', 'Japan'],
  KAZ: ['카자흐스탄', 'Kazakhstan'],
  KEN: ['케냐', 'Kenya'],
  KGZ: ['키르기스스탄', 'Kyrgyzstan'],
  KHM: ['캄보디아', 'Cambodia'],
  KIR: ['키리바시', 'Kiribati'],
  KNA: ['세인트키츠 네비스', 'Saint Kitts and Nevis'],
  KOR: ['대한민국', 'South Korea'],
  KWT: ['쿠웨이트', 'Kuwait'],
  LAO: ['라오스', 'Laos'],
  LBN: ['레바논', 'Lebanon'],
  LBR: ['라이베리아', 'Liberia'],
  LBY: ['리비아', 'Libya'],
  LCA: ['세인트루시아', 'Saint Lucia'],
  LIE: ['리히텐슈타인', 'Liechtenstein'],
  LKA: ['스리랑카', 'Sri Lanka'],
  LSO: ['레소토', 'Lesotho'],
  LTU: ['리투아니아', 'Lithuania'],
  LUX: ['룩셈부르크', 'Luxembourg'],
  LVA: ['라트비아', 'Latvia'],
  MAC: ['마카오', 'Macao'],
  MAF: ['생마르탱', 'Saint Martin'],
  MAR: ['모로코', 'Morocco'],
  MCO: ['모나코', 'Monaco'],
  MDA: ['몰도바', 'Moldova'],
  MDG: ['마다가스카르', 'Madagascar'],
  MDV: ['몰디브', 'Maldives'],
  MEX: ['멕시코', 'Mexico'],
  MHL: ['마셜 제도', 'Marshall Islands'],
  MKD: ['북마케도니아', 'North Macedonia'],
  MLI: ['말리', 'Mali'],
  MLT: ['몰타', 'Malta'],
  MMR: ['미얀마', 'Myanmar'],
  MNE: ['몬테네그로', 'Montenegro'],
  MNG: ['몽골', 'Mongolia'],
  MNP: ['북마리아나 제도', 'Northern Mariana Islands'],
  MOZ: ['모잠비크', 'Mozambique'],
  MRT: ['모리타니', 'Mauritania'],
  MSR: ['몬트세랫', 'Montserrat'],
  MTQ: ['마르티니크', 'Martinique'],
  MUS: ['모리셔스', 'Mauritius'],
  MWI: ['말라위', 'Malawi'],
  MYS: ['말레이시아', 'Malaysia'],
  MYT: ['마요트', 'Mayotte'],
  NAM: ['나미비아', 'Namibia'],
  NCL: ['뉴칼레도니아', 'New Caledonia'],
  NER: ['니제르', 'Niger'],
  NFK: ['노퍽섬', 'Norfolk Island'],
  NGA: ['나이지리아', 'Nigeria'],
  NIC: ['니카라과', 'Nicaragua'],
  NIU: ['니우에', 'Niue'],
  NLD: ['네덜란드', 'Netherlands'],
  NOR: ['노르웨이', 'Norway'],
  NPL: ['네팔', 'Nepal'],
  NRU: ['나우루', 'Nauru'],
  NZL: ['뉴질랜드', 'New Zealand'],
  OMN: ['오만', 'Oman'],
  PAK: ['파키스탄', 'Pakistan'],
  PAN: ['파나마', 'Panama'],
  PCN: ['핏케언 제도', 'Pitcairn Islands'],
  PER: ['페루', 'Peru'],
  PHL: ['필리핀', 'Philippines'],
  PLW: ['팔라우', 'Palau'],
  PNG: ['파푸아뉴기니', 'Papua New Guinea'],
  POL: ['폴란드', 'Poland'],
  PRI: ['푸에르토리코', 'Puerto Rico'],
  PRK: ['북한', 'North Korea'],
  PRT: ['포르투갈', 'Portugal'],
  PRY: ['파라과이', 'Paraguay'],
  PSE: ['팔레스타인', 'Palestine'],
  PYF: ['프랑스령 폴리네시아', 'French Polynesia'],
  QAT: ['카타르', 'Qatar'],
  REU: ['레위니옹', 'Réunion'],
  ROU: ['루마니아', 'Romania'],
  RUS: ['러시아', 'Russia'],
  RWA: ['르완다', 'Rwanda'],
  SAU: ['사우디아라비아', 'Saudi Arabia'],
  SDN: ['수단', 'Sudan'],
  SEN: ['세네갈', 'Senegal'],
  SGP: ['싱가포르', 'Singapore'],
  SGS: ['사우스조지아 사우스샌드위치 제도', 'South Georgia and the South Sandwich Islands'],
  SHN: ['세인트헬레나', 'Saint Helena'],
  SJM: ['스발바르 얀마옌', 'Svalbard and Jan Mayen'],
  SLB: ['솔로몬 제도', 'Solomon Islands'],
  SLE: ['시에라리온', 'Sierra Leone'],
  SLV: ['엘살바도르', 'El Salvador'],
  SMR: ['산마리노', 'San Marino'],
  SOM: ['소말리아', 'Somalia'],
  SPM: ['생피에르 미클롱', 'Saint Pierre and Miquelon'],
  SRB: ['세르비아', 'Serbia'],
  SSD: ['남수단', 'South Sudan'],
  STP: ['상투메 프린시페', 'São Tomé and Príncipe'],
  SUR: ['수리남', 'Suriname'],
  SVK: ['슬로바키아', 'Slovakia'],
  SVN: ['슬로베니아', 'Slovenia'],
  SWE: ['스웨덴', 'Sweden'],
  SWZ: ['에스와티니', 'Eswatini'],
  SXM: ['신트마르턴', 'Sint Maarten'],
  SYC: ['세이셸', 'Seychelles'],
  SYR: ['시리아', 'Syria'],
  TCA: ['터크스 케이커스 제도', 'Turks and Caicos Islands'],
  TCD: ['차드', 'Chad'],
  TGO: ['토고', 'Togo'],
  THA: ['태국', 'Thailand'],
  TJK: ['타지키스탄', 'Tajikistan'],
  TKL: ['토켈라우', 'Tokelau'],
  TKM: ['투르크메니스탄', 'Turkmenistan'],
  TLS: ['동티모르', 'Timor-Leste'],
  TON: ['통가', 'Tonga'],
  TTO: ['트리니다드 토바고', 'Trinidad and Tobago'],
  TUN: ['튀니지', 'Tunisia'],
  TUR: ['튀르키예', 'Türkiye'],
  TUV: ['투발루', 'Tuvalu'],
  TWN: ['대만', 'Taiwan'],
  TZA: ['탄자니아', 'Tanzania'],
  UGA: ['우간다', 'Uganda'],
  UKR: ['우크라이나', 'Ukraine'],
  UMI: ['미국령 군소 제도', 'U.S. Minor Outlying Islands'],
  URY: ['우루과이', 'Uruguay'],
  USA: ['미국', 'United States'],
  UZB: ['우즈베키스탄', 'Uzbekistan'],
  VAT: ['바티칸', 'Vatican City'],
  VCT: ['세인트빈센트 그레나딘', 'Saint Vincent and the Grenadines'],
  VEN: ['베네수엘라', 'Venezuela'],
  VGB: ['영국령 버진아일랜드', 'British Virgin Islands'],
  VIR: ['미국령 버진아일랜드', 'U.S. Virgin Islands'],
  VNM: ['베트남', 'Vietnam'],
  VUT: ['바누아투', 'Vanuatu'],
  WLF: ['왈리스 푸투나', 'Wallis and Futuna'],
  WSM: ['사모아', 'Samoa'],
  XKK: ['코소보', 'Kosovo'],
  YEM: ['예멘', 'Yemen'],
  ZAF: ['남아프리카공화국', 'South Africa'],
  ZMB: ['잠비아', 'Zambia'],
  ZWE: ['짐바브웨', 'Zimbabwe'],
}

export function countryNameOf(iso3: string, locale: Locale): string | undefined {
  const n = COUNTRY_NAMES[iso3]
  return n ? (locale === 'ko' ? n[0] : n[1]) : undefined
}
